Controllers/OgrenciDersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using OgrenciKayit.Models;
using static System.Net.Mime.MediaTypeNames;
using NonFactors.Mvc.Grid;
using System.Security.Cryptography;
using Microsoft.Ajax.Utilities;

namespace OgrenciKayit.Controllers
{
    public class OgrenciDersController : Controller
    {
        private DBOgrenciEntities1 db = new DBOgrenciEntities1();

        // GET: OgrenciDers
        public ActionResult Index()
        {
            
            var ogrenciDers = db.OgrenciDers.Include(o => o.Dersler).Include(o => o.Ogrenci);
            //var ogrenciDers = (from od in db.OgrenciDers
            //                   join d in db.Dersler on od.DersID equals d.DersID
            //                   join o in db.Ogrenci on od.OgrenciID equals o.OgrenciID
            //                   select new
            //                   {
            //                       DersAdi = od.Dersler.Ad,
            //                       OgrenciNo = od.Ogrenci.OgrenciNo,
            //                       Ad = od.Ogrenci.Ad.Trim(),
            //                       Soyad = od.Ogrenci.Soyad.Trim(),
            //                       Yil = od.Yil,
            //                       Donem = od.Donem,
            //                       Vize = od.Vize,
            //                       MazeretVize = od.MazeretVize,
            //                       Final = od.Final,
            //                       Butunleme = od.Butunleme,
            //                       TekDers = od.TekDers,
            //                       BasariNotu = od.BasariNotu,
            //                       HarfNotu = od.HarfNotu



            //                   }).Distinct().ToList();



            return View(ogrenciDers.ToList());
        }
        public ActionResult Transkript(int id)
        {

            Getir();
            var transkriptModel = new TranskriptModel();


            var ogrenciDers = (from od in db.OgrenciDers
                               where od.OgrenciID == id
                               select new OdModel
                               {

                                   DrsAd = od.Dersler.Ad,
                                   DrsKod = od.Dersler.Kodu,
                                   DrsKredi = od.Dersler.Kredi,
                                   DrsEcts = od.Dersler.EctsKredi,
                                   HrfNotu = od.HarfNotu.Trim(),
                                   Yil = od.Yil.Trim(),
                                   Donem = od.Donem.Trim(),

                                   //Yil = (
                                   //         od.Yil == "1" ? "2022-2023" :
                                   //         od.Yil == "2" ? "2023-2024" :
                                   //         od.Yil == "3" ? "2024-2025" :
                                   //         od.Yil == "4" ? "2025-2026" :
                                   //         od.Yil == "5" ? "2026-2027" : "Unknown"
                                   //      ),
                                   //Donem = (
                                   //           od.Donem == "0" ? "Güz" :
                                   //           od.Donem == "1" ? "Bahar" :
                                   //           od.Donem == "2" ? "Yaz" : "Unknown"

                                   //        )

                               }).Distinct().ToList();


            var yilDonemList = (from od in db.OgrenciDers
                                where od.OgrenciID == id
                                select new YilDonem
                                {

                                    Yil = od.Yil.Trim(),
                                    Donem = od.Donem.Trim()



                                }).Distinct().ToList();

            var OgrTrans = (from od in db.OgrenciDers
                            join o in db.Ogrenci on od.OgrenciID equals o.OgrenciID
                            join org in db.Organizasyon on o.OrganizasyonID equals org.ID
                            where od.OgrenciID == id
                            select new OgrTrans
                            {
                                TcKimlikNo = od.Ogrenci.TcKimlikNo,
                                OgrenciNo = od.Ogrenci.OgrenciNo,
                                Ad = od.Ogrenci.Ad,
                                Soyad = od.Ogrenci.Soyad,
                                KayitlanmaYili = od.Ogrenci.KayitlanmaYili,
                                OrganizasyonID = org.ID


                            }).FirstOrDefault();

            transkriptModel.OgrenciDersList = ogrenciDers;
            transkriptModel.YilDonemList = yilDonemList;
            transkriptModel.OgrTrans = OgrTrans;



            return View(transkriptModel);

        }
        public ActionResult Trapor(int id)
        {
            var trapor = new Rotativa.ActionAsPdf("Transkript", new { id = id });
            return trapor;
        }
        //[HttpGet]
        //public PartialViewResult IndexGrid(string search)
        //{
        //    DBOgrenciEntities1 db = new DBOgrenciEntities1();

        //    var ogrenciDers = (from od in db.OgrenciDers
        //                       where od.Dersler.Ad.Contains(search) || od.Ogrenci.OgrenciNo.Contains(search)
        //                       || od.Ogrenci.Ad.Contains(search) || od.Ogrenci.Soyad.Contains(search)
        //                       select new OgrenciDersModel
        //                       {
        //                           DersAdi = od.Dersler.Ad,
        //                           OgrenciNo = od.Ogrenci.OgrenciNo,
        //                           Ad = od.Ogrenci.Ad,
        //                           Soyad = od.Ogrenci.Soyad,
        //                           Yil = od.Yil,
        //                           Donem = od.Donem,
        //                           Vize = od.Vize,
        //                           MazeretVize = od.MazeretVize,
        //                           Final = od.Final,
        //                           Butunleme = od.Butunleme,
        //                           TekDers = od.TekDers,
        //                           BasariNotu = od.BasariNotu,
        //                           HarfNotu = od.HarfNotu


        //                       }).ToList();



        //    return PartialView("_IndexGrid", ogrenciDers);
        //}



        [HttpPost]
        public JsonResult SearchAll(string yazilan)
        {
            DBOgrenciEntities1 db = new DBOgrenciEntities1();
            //var ogrenciDers = db.OgrenciDers.Where(x => x.Dersler.Ad.Contains(customerName)).Select(x => x.Ogrenci).ToList();
            //var ogrenciDers = (from od in db.OgrenciDers
            //                   where od.Dersler.Ad.Contains(customerName)
            //                   select new OgrenciDersModel
            //                   {
            //                       DersAdi = od.Dersler.Ad,
            //                       OgrenciNo = od.Ogrenci.OgrenciNo,
            //                       Ad = od.Ogrenci.Ad,
            //                       Soyad = od.Ogrenci.Soyad,
            //                       Vize = od.Vize ?? 0
            //                   }).ToList();


            //var ogrenciDers = (from o in db.Ogrenci
            //                   join od in db.OgrenciDers on o.OgrenciID equals od.OgrenciID
            //                   join d in db.Dersler on od.DersID equals d.DersID
            //                   where d.Ad.Contains(customerName)
            //                   select new
            //                   {
            //                       d.Ad,
            //                       o.OgrenciNo,
            //                       o.Ad,
            //                       o.Soyad


            //                   }).ToList();

            //return Json(ogrenciDers, JsonRequestBehavior.AllowGet);
            var ogrenciDers = (from od in db.OgrenciDers
                               where od.Dersler.Ad.Contains(yazilan) || od.Ogrenci.OgrenciNo.Contains(yazilan)
                               || od.Ogrenci.Ad.Contains(yazilan) || od.Ogrenci.Soyad.Contains(yazilan)
                               select new OgrenciDersModel
                               {
                                   DersAdi = od.Dersler.Ad,
                                   OgrenciNo = od.Ogrenci.OgrenciNo,
                                   Ad = od.Ogrenci.Ad,
                                   Soyad = od.Ogrenci.Soyad,
                                   Yil = od.Yil,
                                   Donem = od.Donem,
                                   Vize = od.Vize,
                                   MazeretVize = od.MazeretVize,
                                   Final = od.Final,
                                   Butunleme = od.Butunleme,
                                   TekDers = od.TekDers,
                                   BasariNotu = od.BasariNotu,
                                   HarfNotu = od.HarfNotu


                               }).ToList();





            return Json(ogrenciDers, JsonRequestBehavior.AllowGet);
        }

        // GET: OgrenciDers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OgrenciDers ogrenciDers = db.OgrenciDers.Find(id);
            if (ogrenciDers == null)
            {
                return HttpNotFound();
            }

Views/Ogrencis/Delete.cshtml
@model OgrenciKayit.Models.Ogrenci

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="~/Scripts/jquery-3.4.1.js"></script>
<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/alertify.min.js"></script>
<link href="~/Content/themes/alertify.core.css" rel="stylesheet" />
<link href="~/Content/themes/alertify.default.css" rel="stylesheet" />




<h2>Silmek istediğinize emin misiniz?</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayName("Öğrenci Numarası")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OgrenciNo)
        </dd>

        <dt>
            @Html.DisplayName("Ad")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ad)
        </dd>

        <dt>
            @Html.DisplayName("Soyad")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Soyad)
        </dd>

        <dt>
            @Html.DisplayName("TC Kimlik Numarası")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TcKimlikNo)
        </dd>

        <dt>
            @Html.DisplayName("Doğum Tarihi")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DogumTarihi)
        </dd>

        <dt>
            @Html.DisplayName("Telefon")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Telefon)
        </dd>

        <dt>
            @Html.DisplayName("E-mail")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayName("Adres")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Adres)
        </dd>

        <dt>
            @Html.DisplayName("Uyruk")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Uyrugu)
        </dd>

        <dt>
            @Html.DisplayName("Organizasyon")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Organizasyon.Ad)
        </dd>

        <dt>
            @Html.DisplayName("Sınıf")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sinif)
        </dd>

        <dt>
            @Html.DisplayName("Müfredat")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Mufredat)
        </dd>

        <dt>
            @Html.DisplayName("Mezuniyet Tarihi")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MezuniyetTarihi)
        </dd>

        <dt>
            @Html.DisplayName("Bitirdiği Üniversite")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BitirdigiUniversite)
        </dd>

        <dt>
            @Html.DisplayName("Yarıyılı")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Yariyili)
        </dd>

        <dt>
            @Html.DisplayName("Eğitim Türü")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EgitimTuru)
        </dd>

        <dt>
            @Html.DisplayName("Borçluluk Durumu")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BorclulukDurumu)
        </dd>

        <dt>
            @Html.DisplayName("Kulüp Üyeliği")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.KulupUyeligi)
        </dd>

        <dt>
            @Html.DisplayName("Kayıtlanma Şekli")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.KayitlanmaSekli)
        </dd>

        <dt>
            @Html.DisplayName("Kayıtlanma Puanı")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.KayitlanmaPuani)
        </dd>

        <dt>
            @Html.DisplayName("Kayıtlanma Yılı")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.KayitlanmaYili)
        </dd>

        <dt>
            @Html.DisplayName("Kayıtlanma Dönemi")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.KayitDonemi)
        </dd>

        <dt>
            @Html.DisplayName("Lise Mezuniyeti")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LiseMezuniyeti)
        </dd>

        <dt>
            @Html.DisplayName("Lise Mezuniyeti Puanı")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LiseMezuniyetiPuani)
        </dd>

        <dt>
            @Html.DisplayName("Cinsiyet")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cinsiyet)
        </dd>

        <dt>
            @Html.DisplayName("Askerlik Durumu")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AskerlikDurumu)
        </dd>

        <dt>
            @Html.DisplayName("Engellilik Durumu")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EngellilikDurumu)
        </dd>

    </dl>


    <div class="form-actions no-color">
        <input type="submit" value="Sil" id="dlt" onclick="AjaxFormSubmit()" class="btn btn-danger" /> |
        @Html.ActionLink("Geri Dön", "Index")
    </div>

</div>
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
<script type="text/javascript" src="https://ajax.cdnjs.com/ajax/libs/json2/20110223/json2.js"></script>
<script>
        //var btn = document.getElementById("dlt");

        alertify.set({ labels: { ok: "Tamam" } });


        function AjaxFormSubmit() {

            var person = {};
            person.Id = @Model.OgrenciID;
 
            $.ajax({
                type: "POST",
                url: '/Ogrencis/DeleteConfirmed',
                data: JSON.stringify(person),
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                success: function (response) {
                    if (response.result == true) {
                        alertify.alert("Öğrenci başarıyla silindi!", function () {
                            window.location.href ='/Ogrencis/Index';
                        });
                    }
                    else {
                        alertify.alert(response.error);
                    }
                },
                error: function (response) {
                    console.log(response)
                }
            });



        }



</script>



<!--<script>
        var btn = document.getElementById("dlt");

        alertify.set({ labels: { ok: "Tamam" } });


        btn.onclick = function () {-->
@*var OgrId =@Model.OgrenciID;*@

<!--if (@ViewData["data"]== 0) {
            alertify.alert("Öğrenciye ait ilişkili kayıtlar olduğu için silinemez!")
            return false;

        }






    }



</script>-->

Views/Ogrencis/Details.cshtml
@model OgrenciKayit.Models.Ogrenci

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h3>Detaylar</h3>
<br />
<img src="~/Fotograf/@Model.Fotograf" />
<br />
<br />
@*@Html.ActionLink("Öğrenci Belgesi", "OgrenciRaporu", new { id = Model.OgrenciID })*@
<input type="button" class="btn btn-primary" value="Öğrenci Belgesi" onclick="location.href='@Url.Action("OgrenciRaporu", new { id = Model.OgrenciID })'" />
<br />
<br />
<input type="button" class="btn btn-primary" value="Transkript" onclick="location.href='@Url.Action("Trapor", "OgrenciDers", new { id = Model.OgrenciID }, null)'" />

@*@Html.ActionLink("Transkript", "Trapor", "OgrenciDers", new { id = Model.OgrenciID }, null)*@


<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayName("Öğrenci Numarası")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OgrenciNo)
        </dd>

        <dt>
            @Html.DisplayName("Ad")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ad)
        </dd>

        <dt>
            @Html.DisplayName("Soyad")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Soyad)
        </dd>


        <dt>
            @Html.DisplayName("Anne Adı")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AnneAd)
        </dd>


        <dt>
            @Html.DisplayName("Baba Adı")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BabaAd)
        </dd>

        <dt>
            @Html.DisplayName("TKimlik Numarası")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TcKimlikNo)
        </dd>

        <dt>
            @Html.DisplayName("Doğum Tarihi")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DogumTarihi)
        </dd>

        <dt>
            @Html.DisplayName("Telefon")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Telefon)
        </dd>

        <dt>
            @Html.DisplayName("E-mail")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayName("Adres")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Adres)
        </dd>

        <dt>
            @Html.DisplayName("Uyruk")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Uyrugu)
        </dd>

        <dt>
            @Html.DisplayName("Organizasyon")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Organizasyon.Ad)
        </dd>

        <dt>
            @Html.DisplayName("Sınıf")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sinif)
        </dd>

        <dt>
            @Html.DisplayName("Müfredat")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Mufredat)
        </dd>

        <dt>
            @Html.DisplayName("Mezuniyet Tarihi")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MezuniyetTarihi)
        </dd>

        <dt>
            @Html.DisplayName("Bitirdiği Üniversite")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BitirdigiUniversite)
        </dd>

        <dt>
            @Html.DisplayName("Yarıyılı")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Yariyili)
        </dd>

        <dt>
            @Html.DisplayName("Eğitim Türü")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EgitimTuru)
        </dd>

        <dt>
            @Html.DisplayName("Borçluluk Durumu")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BorclulukDurumu)
        </dd>

        <dt>
            @Html.DisplayName("Kulüp Üyeliği")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.KulupUyeligi)
        </dd>

        <dt>
            @Html.DisplayName("Kayıtlanma Şekli")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.KayitlanmaSekli)
        </dd>

        <dt>
            @Html.DisplayName("Kayıtlanma Puanı")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.KayitlanmaPuani)
        </dd>

        <dt>
            @Html.DisplayName("Kayıtlanma Yılı")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.KayitlanmaYili)
        </dd>
        <dt>
            @Html.DisplayName("Öğrenim Süresi")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OgrSure)
        </dd>
        <dt>
            @Html.DisplayName("Kayıtlanma Dönemi")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.KayitDonemi)
        </dd>

        <dt>
            @Html.DisplayName("Lise Mezuniyeti")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LiseMezuniyeti)
        </dd>

        <dt>
            @Html.DisplayName("Lise Mezuniyeti Puanı")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LiseMezuniyetiPuani)
        </dd>

        <dt>
            @Html.DisplayName("Cinsiyet")
        </dt>

        <dd>
            @if (Model.Cinsiyet == "0         ")
            {
                @Html.DisplayName("Erkek")
            }
            else if (Model.Cinsiyet == "1         ")
            {
                @Html.DisplayName("Kadın")
            }
        </dd>

        <dt>
            @Html.DisplayName("Askerlik Durumu")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AskerlikDurumu)
        </dd>

        <dt>
            @Html.DisplayName("Engellilik Durumu")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EngellilikDurumu)
        </dd>
        <dt>
            @Html.DisplayName("Öğrencilik Hakkı")
        </dt>
        <dd>
            @if (Model.OgrHak == true)
            {
                @Html.DisplayName("Evet")
            }
            else
            {
                @Html.DisplayName("Hayır")
            }
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Düzenle", "Edit", new { id = Model.OgrenciID }) |
    @Html.ActionLink("Geri Dön", "Index")
</p>

Views/Ogrencis/Index.cshtml
@model IEnumerable<OgrenciKayit.Models.Ogrenci>


@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
<h2 style="position:relative; top:50px;">Öğrenci Listesi</h2>
<br />
<h3 style="position:relative; padding-left:1130px">
    @Html.ActionLink("Öğrenci Ekle", "Create")
</h3>


<table class="table">
    <tr>
        <th>
            @Html.DisplayName("Öğrenci Numarası")
        </th>
        <th>
            @Html.DisplayName("Ad")
        </th>
        <th>
            @Html.DisplayName("Soyad")
        </th>
        <th>
            @Html.DisplayName("TC Kimlik Numarası")
        </th>
        <th>
            @Html.DisplayName("Doğum Tarihi")
        </th>
        <th>
            @Html.DisplayName("Telefon")
        </th>
        <th>
            @Html.DisplayName("E-mail")
        </th>
        <th>
            @Html.DisplayName("Adres")
        </th>
        <th>
            @Html.DisplayName("Uyruk")
        </th>
        <th>
            @Html.DisplayName("Organizasyon")
        </th>
        <th>
            @Html.DisplayName("Sınıf")
        </th>
        <th style="padding-left:50px">
            @Html.DisplayName("Fotoğraf")
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.OgrenciNo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ad)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Soyad)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TcKimlikNo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DogumTarihi)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Telefon)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Adres)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Uyrugu)
            </td>
            <td>
                @foreach (var item1 in ViewBag.parent)
                {
                    if (item1.ID == item.OrganizasyonID)
                    {
                        @item1.Ad
                        break;
                    }

                }

            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Sinif)
            </td>
            <td>
                <img src="~/Fotograf/@item.Fotograf" />

                @*<img src="@Url.Content(item.Fotograf)" alt="Image" />*@

            </td>
            <td>
                @Html.ActionLink("Detay", "Details", new { id = item.OgrenciID })
                @Html.ActionLink("Düzenle", "Edit", new { id = item.OgrenciID }) <br />
                @Html.ActionLink("Sil", "Delete", new { id = item.OgrenciID })
            </td>
        </tr>

    }

</table>

Views/Ogrencis/OgrenciBelgesi.cshtml
@model OgrenciKayit.Models.Ogrenci

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>OgrenciBelgesi</title>
    <style type="text/css">

        .konum {
            position: relative;
            padding-left: 100px;
        }
    </style>
</head>
<body>

    <img style="position:absolute; padding-left: 100px; top:140px" src="~/Fotograf/m.png" />
    <img style="position: relative; padding-left: 650px; top: 115px" src="~/Fotograf/y.png" />
    @Html.Label(DateTime.Now.ToLongDateString(), new {@style= "position: relative; padding-left: 660px; top: 110px" });
    <center><p><b>T.C.</b><br /><b> YÜKSEKÖĞRETİM KURULU BAŞKANLIĞI</b> <br /><b>ANKARA</b></p></center>
    <center><br /><p><b>ÖĞRENCİ BELGESİ</b></p></center>
    <br />
    <p class="konum"><b>T.C. Kimlik No:</b> @Model.TcKimlikNo </p>
    <p class="konum"><b>Adı:</b> @Model.Ad </p>
    <p class="konum"><b>Soyadı:</b> @Model.Soyad </p>
    <p class="konum"><b>Anne Adı:</b> @Model.AnneAd </p>
    <p class="konum"><b>Baba Adı:</b> @Model.BabaAd </p>
    <p class="konum"><b>Doğum Tarihi:</b> @Model.DogumTarihi.Value.ToShortDateString()</p>
    <p class="konum"><b>Uyruğu: </b>@Model.Uyrugu</p>
    <p class="konum"><b>Sınıfı: </b>@Model.Sinif</p>
    <p class="konum"><b>Kayıt Tarihi: </b>@Model.KayitlanmaYili.Value.ToShortDateString()</p>
    <p class="konum">
        <b>Üniversite/Fakülte/MYO/YO/Enstütü/Bölüm/Program: </b>

        @foreach (var item in ViewBag.parent)
        {
            if (item.ID == Model.OrganizasyonID)
            {
                @item.Ad
                break;
            }

        }

    </p>
    <p class="konum"><b>Eğitim Türü: </b>@Model.EgitimTuru</p>
    <p class="konum"><b>Öğrenim Süresi: </b>@Model.OgrSure</p>
    @if (Model.OgrHak == true)
    {
        <p class="konum"><b>Öğrencilik Hakkı Var mı?: </b>Evet</p>
    }
    else
    {
        <p class="konum"><b>Öğrencilik Hakkı Var mı?: </b>Hayır</p>
    }
    <center><br /><b>İLGİLİ MAKAMA</b><br /><br />Yukarıda kimlik bilgileri verilen öğrenci MARMARA ÜNİVERSİTESİ öğrencisidir.</center>



</body>
</html>